### ISSUE TITLE
Online tester v3 command expected input problem

### ISSUE THREAD

**Issue by GeorgiyGit** [FedorViest/opp_prpr2024#3]
In the online tester, v3 command expected output contains:
```
ID. mer. modulu: ***
Hodnota 1: ***
Hodnota 2: ***
Poznamka C: *** : *** => ***
Poznamka T: ***
```
In that time, documentation contains one more line `Poznamka ID: ***` before `Poznamka C:`
![image](https://github.com/user-attachments/assets/d00f6721-84b8-407a-ac91-9dbb5167f7b1)

Shouldn`t the expected output in v3 also contain this line? In this case, expected output will be:
```
ID. mer. modulu: ***
Hodnota 1: ***
Hodnota 2: ***
Poznamka ID: ***
Poznamka C: *** : *** => ***
Poznamka T: ***
```

This is the screen from online tester with this error:
![image](https://github.com/user-attachments/assets/2230cfcf-8f60-4f2a-9911-0194466b0bfa)
(The same expected output pattern is in the other tests which contain v3)

If the problem is in my code, and the tester works as expected, please write me something? If the online tester is not yours, forget about this issue...

**Comment by WhenGrill** [comment]
We do not provide support for the online tester as we are not authors of the online interface, nor are we authors of the tests that you show here. I cannot provide support without knowing what tests are running on the background.

**Comment by FedorViest** [comment]
In case of issues with online version of tester write on the email provided on the tester website, as we dont have any more information about online tester as you
![image](https://github.com/user-attachments/assets/df70a680-8102-4add-acba-0cfa7f66ed13)
